config/routes.rb
Rails.application.routes.draw do
  root 'subscriptions#new'

  resource 'subscriptions'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	attr_accessor :full_name
	attr_accessor :email
	attr_accessor :telephone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def new
		@subscription = Subscription.new
  end

  def create
		Stripe.api_key = "sk_test_784Tfetqy9nGz4iTgMpyCkb9"
		token = params[:subscription][:card_token]

		begin
		  charge = Stripe::Charge.create(
		    :amount => 10000, # Amount in cents
		    :currency => "usd",
		    :source => token,
		    :description => "Example charge"
		  )
		rescue Stripe::CardError => e
		end
	end



	private

  def subscription_params
    params.require(:subscription).permit( :full_name, :telephone, :email, :card_token)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomForm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subscriptions/create.html.erb
<h1>Subscriptions#create</h1>
<p>Find me in app/views/subscriptions/create.html.erb</p>

app/views/subscriptions/new.html.erb
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script>
	Stripe.setPublishableKey("pk_test_6O0iBT71KxVHeUCuWeTpNZlS");
</script>
<%= javascript_include_tag "credit_card_form.js" %>
<div class="">
	<%= form_for @subscription, as: :subscription, url: subscriptions_path do |f| %>
		<% if @subscription.errors.any? %>
			<div id="error_explanation">
				<h2>
					<%= pluralize(@subscription.errors.count, "error") %>
					prohibited this subscription from being saved:
				</h2>
				<ul>
					<% @subscription.errors.full_messages.each do |message| %>
					<li>
						<%= message %>
					</li>
					<% end %>
				</ul>
			</div>
		<% end %>
		<div class="field">
			<%= f.label :full_name %>
			<%= f.text_field :full_name %>
		</div>
		<div class="field">
			<%= f.label :email %>
			<%= f.text_field :email %>
		</div>
		<div class="field">
			<%= f.label :telephone %>
			<%= f.text_field :telephone %>
		</div>
		<%= label_tag "Card Number", nil, required: true %>
		<div class="control-group">
			<div class="controls">
				<%= text_field_tag :card_number, nil, class: "input-block-level", "data-stripe" => "number" %>
			</div>
		</div>
		<%= label_tag "Card Verification Code", nil, required: true %>
		<div class="control-group">
			<div class="controls">
				<%= text_field_tag :card_verification, nil, class: "input-block-level", "data-stripe" => "cvv" %>
			</div>
		</div>
		<%= label_tag "Card Expires", nil, required: true %>
		<%= select_tag :exp_month, options_for_select(Date::MONTHNAMES.compact.each_with_index.map { |name,i| ["#{i+1} - #{name}", i+1] }), include_blank: false, "data-stripe" => "exp-month", class: "span2" %>
		<%= select_tag :exp_year, options_for_select((Date.today.year..(Date.today.year+10)).to_a), include_blank: false, "data-stripe" => "exp-year", class: "span1" %>
		<div class="actions">
			<%= f.submit "Subscription Payment", class: "btn", style: "color: white;background: rgb(242, 118, 73);" %>
		</div>
	<% end %>
</div>
	<!-- <%= javascript_include_tag "https://js.stripe.com/v2/" %> -->